# -*- coding: utf-8 -*-
"""Aula05+6.1.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dXUe91UicQ9LOqKOvkX87WcdATqHd_kj
"""

nomes = []
idades = []
alturas = []

cadastro = int(input('quantas pessoas vamos cadastrar?'))
#contador
c = 1 
#indices
i = 0 
while c <= cadastro:
    nome = str(input('informe o nome:'))
    idade = int(input('informe a idade:'))
    altura = float(input('informe a sua altura:'))
    nomes.append(nome)
    idades.append(idade)
    alturas.append(altura)
    c+=1
while i<= cadastro -1:
    print(f'nome: {nomes[i]}, idade: {idades[i]}, altura: {alturas[i]}') 
    i+=1

alunos = []
while True:
    resposta = int(input(''' opção 1 cadastra aluno
opção 2 atualizar aluno
opção 3 excluir aluno
opção 4 pesquisar aluno
opção 5 ver lista de alunos
opção 6 sair
'''))
#opção 1
    if resposta == 1:
        aluno = str(input('informe o nome do aluno:')).upper()
        alunos.append(aluno)
        print(f'{aluno} foi adcionado com sucesso.')
        continuar = str(input('digite enter para continuar ou SAIR para sair'))
        if continuar == '':
            pass
        else:
            break
#opção 2            
    elif resposta == 2:
        busca_aluno = str(input('informe o nome do aluno que recebera a atualizaçao:')).upper()
        if busca_aluno in alunos:
            att_aluno = str(input(f'atualize {busca_aluno}!')).upper()
            i = alunos.index(busca_aluno)
            alunos.pop(i)
            alunos.append(att_aluno)
            print(f'{att_aluno} atalizado com sucesso')
        else:
            print(f'{busca_aluno} nao foi encontrado de alunos cadastrado.')
#opção 3            
    elif resposta == 3:
        busca_aluno = str(input('informe o nome do aluno que deseja excluir:'))
        if busca_aluno in alunos:
            i = alunos.index(busca_aluno)
            alunos.pop(i)
            print(f'{busca_aluno} excluido com sucesso')
        else:
            print(f'{busca_aluno} nao cadastrado')
#opção 4
    elif resposta == 4:
        busca_aluno = str(input('digite o nome do aluno que voce esta procurando!')).upper()
        if busca_aluno in alunos:
            print(f'{busca_aluno} esta cadastrado no indece {alunos.index(busca_aluno)}.')
        else:
            print(f'{busca_aluno} nao esta registrado.')
#opção 5
    elif resposta == 5:
        print('## - nome')
        for aluno in alunos:
            print(f'{alunos.index(aluno)} - {aluno}')
#opçaõ 6
    elif resposta == 6:
        break
    else:
        print('insere uma resposta valida!')